/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectotienda;

import cosas_emp.Archivo;
import cosas_emp.Busqueda;
import cosas_emp.Empleado;
import cosas_emp.Reportes;
import cosas_prod.Producto;
import cosas_prov.Reportesprov;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alan Nava Martinez
 */
public class co_pr extends javax.swing.JFrame {

    /**
     * Creates new form co_pr
     */
    public co_pr() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        id_emp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        id_pro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ca_co_pro = new javax.swing.JTextField();
        comp_pro = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        compras = new javax.swing.JTable();
        prov = new javax.swing.JButton();
        empl = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Introduce id del empleado que atiende");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 7, 210, 21));

        id_emp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                id_empKeyTyped(evt);
            }
        });
        getContentPane().add(id_emp, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 178, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Introduce id del producto a comprar");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 40, 200, -1));

        id_pro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                id_proKeyTyped(evt);
            }
        });
        getContentPane().add(id_pro, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 178, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cantidad del producto a comprar");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 74, -1, -1));

        ca_co_pro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ca_co_proKeyTyped(evt);
            }
        });
        getContentPane().add(ca_co_pro, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 178, -1));

        comp_pro.setText("Comprar");
        comp_pro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comp_proActionPerformed(evt);
            }
        });
        getContentPane().add(comp_pro, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, -1, -1));

        compras.setBackground(new java.awt.Color(153, 153, 153));
        compras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Categoria", "Stock", "Nombre", "Precio", "Piezas compradas", "Total"
            }
        ));
        jScrollPane2.setViewportView(compras);

        jScrollPane1.setViewportView(jScrollPane2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 99, 460, 100));

        prov.setText("Provedores");
        prov.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provActionPerformed(evt);
            }
        });
        getContentPane().add(prov, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        empl.setText("Empleados");
        empl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emplActionPerformed(evt);
            }
        });
        getContentPane().add(empl, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1.2.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 280));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void id_empKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_empKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        boolean num = key >= 48 && key <= 57;
        
        
        if(!num && (key != KeyEvent.VK_BACK_SPACE) && (key != KeyEvent.VK_ENTER)){
            evt.consume();
            JOptionPane.showMessageDialog(this, "No puede ingresar letras");
        }
        
        if(id_emp.getText().trim().length() == 7 && (key != KeyEvent.VK_BACK_SPACE) && (key != KeyEvent.VK_ENTER)){
            evt.consume();
           
            JOptionPane.showMessageDialog(this, "No puede ser mayor a 7 digitos");
        }
    }//GEN-LAST:event_id_empKeyTyped

    private void id_proKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_id_proKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        boolean num = key >= 48 && key <= 57;
        
        
        if(!num && (key != KeyEvent.VK_BACK_SPACE) && (key != KeyEvent.VK_ENTER)){
            evt.consume();
            JOptionPane.showMessageDialog(this, "No puede ingresar letras");
        }
        
        if(id_pro.getText().trim().length() == 7 && (key != KeyEvent.VK_BACK_SPACE) && (key != KeyEvent.VK_ENTER)){
            evt.consume();
           
            JOptionPane.showMessageDialog(this, "No puede ser mayor a 7 digitos");
        }
    }//GEN-LAST:event_id_proKeyTyped

    private void ca_co_proKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ca_co_proKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        boolean num = key >= 48 && key <= 57;
        
        
        if(!num && (key != KeyEvent.VK_BACK_SPACE) && (key != KeyEvent.VK_ENTER)){
            evt.consume();
            JOptionPane.showMessageDialog(this, "No puede ingresar letras");
        }
        
        if(ca_co_pro.getText().trim().length() == 7 && (key != KeyEvent.VK_BACK_SPACE) && (key != KeyEvent.VK_ENTER)){
            evt.consume();
           
            JOptionPane.showMessageDialog(this, "No puede ser mayor a 7 digitos");
        }
    }//GEN-LAST:event_ca_co_proKeyTyped

    private void comp_proActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comp_proActionPerformed
        // TODO add your handling code here:
        if(id_emp.getText().length() == 0){
            JOptionPane.showMessageDialog(this, "Faltan campos a llenar");
        }
        else if(id_pro.getText().length() == 0){
            JOptionPane.showMessageDialog(this, "Faltan campos a llenar");
        }
        else if(ca_co_pro.getText().length() == 0){
            JOptionPane.showMessageDialog(this, "Faltan campos a llenar");
        }
        else{
        int po = -1;
        ArrayList<Empleado> emps;
        emps = Archivo.leer("emps.dat");
        int id, cop;
        id = Integer.parseInt(id_emp.getText());
        cop = Integer.parseInt(ca_co_pro.getText());
        
        
            try {
                po = Busqueda.buscarIdArrayList(emps, id);
            } catch (IOException ex) {
                Logger.getLogger(co_pr.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        
        if(po != -1){
            emps.get(po);
           JOptionPane.showMessageDialog(this,"El empleado que lo atiende es: "+ emps.get(po).getNom() + " " +emps.get(po).getApe());
            emps.get(po).getId();
            emps.get(po).getNom();
            emps.get(po).getApe();
            emps.get(po).getEdad();
                        
        }
        else{
            JOptionPane.showMessageDialog(this,"El id consultado: "+ id + "no existe");
            id_emp.setText(null);
        }
        
        int po1 = -1;
        ArrayList<Producto> prodc;
        DefaultTableModel m;
        prodc = Archivo.leer("prodc.dat");
        int idp;
        idp = Integer.parseInt(id_pro.getText());
        
        
            try {
                po1 = Busqueda.buscarIdpArrayList(prodc, idp);
            } catch (IOException ex) {
                Logger.getLogger(co_pr.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        
        if(po1 != -1){
            
            if(cop > prodc.get(po1).getStock()){
                JOptionPane.showMessageDialog(this, "No puede comprar mas de lo que hay en stock");
                ca_co_pro.setText(null);
            }
            else{
            prodc.get(po1);
            
            m = (DefaultTableModel)compras.getModel();
            Object[] rowData = new Object[7];

            prodc.get(po1).setStock(prodc.get(po1).getStock() - cop);
            
            rowData[0] = prodc.get(po1).getId();
            rowData[1] = prodc.get(po1).getCategoria();
            rowData[2] = prodc.get(po1).getStock();
            rowData[3] = prodc.get(po1).getNombre();
            rowData[4] = prodc.get(po1).getPrecio();
            rowData[5] = cop;
            rowData[6] = prodc.get(po1).getPrecio() * cop;
            m.addRow(rowData);
            
            Archivo.guardar(prodc, "prodc.dat");
            }
        }
        else{
            JOptionPane.showMessageDialog(this,"El id del producto: "+ id + "no existe");
            ca_co_pro.setText(null);
        }
        
        id_pro.setText(null);
        ca_co_pro.setText(null);
        }
    }//GEN-LAST:event_comp_proActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_cancelarActionPerformed

    private void provActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provActionPerformed
        // TODO add your handling code here:
        Reportesprov rep;
        rep = new Reportesprov();
        rep.setVisible(true);
    }//GEN-LAST:event_provActionPerformed

    private void emplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emplActionPerformed
        // TODO add your handling code here:
        Reportes rep;
        rep = new Reportes();
        rep.setVisible(true);
    }//GEN-LAST:event_emplActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(co_pr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(co_pr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(co_pr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(co_pr.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new co_pr().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ca_co_pro;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton comp_pro;
    private javax.swing.JTable compras;
    private javax.swing.JButton empl;
    private javax.swing.JTextField id_emp;
    private javax.swing.JTextField id_pro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton prov;
    // End of variables declaration//GEN-END:variables
}
