/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectotienda;

import cosas_prov.Menu_provedores;
import cosas_prod.Menu_productos;
import cosas_emp.Menu_Empleado;
import javax.swing.JOptionPane;

/**
 *
 * @author Alan Nava Martinez
 */
public class Proyecto_tienda extends javax.swing.JFrame {

    /**
     * Creates new form Proyecto_tienda
     */
    public Proyecto_tienda() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        Me = new javax.swing.JButton();
        prod = new javax.swing.JButton();
        prove = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        Compra = new javax.swing.JButton();
        Reportes = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("                    UwU Store");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 210, 31));

        Me.setBackground(new java.awt.Color(153, 153, 153));
        Me.setText("Menu Empleados");
        Me.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MeActionPerformed(evt);
            }
        });
        getContentPane().add(Me, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 100, 123, 40));

        prod.setBackground(new java.awt.Color(153, 153, 153));
        prod.setText("Menu Productos");
        prod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodActionPerformed(evt);
            }
        });
        getContentPane().add(prod, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, 40));

        prove.setBackground(new java.awt.Color(153, 153, 153));
        prove.setText("Menu Provedores");
        prove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proveActionPerformed(evt);
            }
        });
        getContentPane().add(prove, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 165, -1, 40));

        exit.setBackground(new java.awt.Color(153, 153, 153));
        exit.setText("Salir");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 217, 118, 40));

        Compra.setBackground(new java.awt.Color(153, 153, 153));
        Compra.setText("Comprar");
        Compra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompraActionPerformed(evt);
            }
        });
        getContentPane().add(Compra, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 165, 118, 40));

        Reportes.setBackground(new java.awt.Color(153, 153, 153));
        Reportes.setText("Reportes");
        Reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportesActionPerformed(evt);
            }
        });
        getContentPane().add(Reportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(79, 217, 123, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/2.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1f (1).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 430, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MeActionPerformed
        // TODO add your handling code here:
        Menu_Empleado mnem;
        mnem = new Menu_Empleado();
        
        if(mnem.isVisible() == true){
            mnem.dispose();
        }
        else{
            mnem.setVisible(true);
        }
    }//GEN-LAST:event_MeActionPerformed

    private void prodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodActionPerformed
        // TODO add your handling code here:
        Menu_productos mpr;
        mpr = new Menu_productos();
        mpr.setVisible(true);
    }//GEN-LAST:event_prodActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "profe pongame 10 plis UwU");

        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void proveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proveActionPerformed
        // TODO add your handling code here:
        Menu_provedores mpe;
        mpe = new Menu_provedores();
        mpe.setVisible(true);
    }//GEN-LAST:event_proveActionPerformed

    private void CompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompraActionPerformed
        // TODO add your handling code here:
        co_pr cr;
        cr = new co_pr();
        cr.setVisible(true);
    }//GEN-LAST:event_CompraActionPerformed

    private void ReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportesActionPerformed
        // TODO add your handling code here:
        Reportesto res;
        res = new Reportesto();
        res.setVisible(true);
    }//GEN-LAST:event_ReportesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proyecto_tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proyecto_tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proyecto_tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proyecto_tienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proyecto_tienda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Compra;
    private javax.swing.JButton Me;
    private javax.swing.JButton Reportes;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton prod;
    private javax.swing.JButton prove;
    // End of variables declaration//GEN-END:variables
}
