/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectotienda;

import cosas_emp.Archivo;
import cosas_emp.Empleado;
import cosas_prod.Producto;
import cosas_prov.Provedores;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alan Nava Martinez
 */
public class Reportesto extends javax.swing.JFrame {

    /**
     * Creates new form Reportesto
     */
    public Reportesto() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        DefaultTableModel m1;
        ArrayList<Empleado> emps;
        emps = Archivo.leer("emps.dat");
        
        m1 = (DefaultTableModel)Reportes.getModel();
        Object[] rowData = new Object[7];
        if(m1.getRowCount() == 0){
            for(Empleado e: emps){
                if(e instanceof Empleado){
                    rowData[0] = ((Empleado)e).getId();
                    rowData[1] = ((Empleado)e).getNom();
                    rowData[2] = ((Empleado)e).getApe();
                    rowData[3] = ((Empleado)e).getEdad();
                    rowData[4] = ((Empleado)e).gethT();
                    rowData[5] = ((Empleado)e).getpH();
                    rowData[6] = ((Empleado)e).gethT()*((Empleado)e).getpH();
                    m1.addRow(rowData);
                }
            }
        }        
        
        DefaultTableModel m2;        
        ArrayList<Producto> prodc;
        prodc = Archivo.leer("prodc.dat");
        
        m2 = (DefaultTableModel)Reportes2.getModel();
        Object[] rowData2 = new Object[5];

        if(m2.getRowCount() == 0){
            for(Producto p: prodc){
                if(p instanceof Producto){
                    rowData2[0] = ((Producto)p).getId();
                    rowData2[1] = ((Producto)p).getCategoria();
                    rowData2[2] = ((Producto)p).getStock();
                    rowData2[3] = ((Producto)p).getNombre();
                    rowData2[4] = ((Producto)p).getPrecio();
                    m2.addRow(rowData2);
                }
            }
        }    
        
        DefaultTableModel m3;
        ArrayList<Provedores> prov;
        prov = Archivo.leer("prov.dat");

        m3 = (DefaultTableModel)Reportes3.getModel();
        Object[] rowData3 = new Object[6];
        if(m3.getRowCount() == 0){
            for(Provedores e: prov){
                if(e instanceof Provedores){
                    rowData3[0] = ((Provedores)e).getId();
                    rowData3[1] = ((Provedores)e).getNombre();
                    rowData3[2] = ((Provedores)e).getApellido();
                    rowData3[3] = ((Provedores)e).getMarca();
                    rowData3[4] = ((Provedores)e).getcT();
                    rowData3[5] = ((Provedores)e).gettot();
                    m3.addRow(rowData3);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        j1 = new javax.swing.JScrollPane();
        Reportes1 = new javax.swing.JTable();
        j = new javax.swing.JScrollPane();
        Reportes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        j2 = new javax.swing.JScrollPane();
        Reportes2 = new javax.swing.JTable();
        j3 = new javax.swing.JScrollPane();
        Reportes3 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        regresar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel2.setText("REPORTES PRODUCTO");

        Reportes1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Categoria", "Stock", "Nombre", "precio"
            }
        ));
        j1.setViewportView(Reportes1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Reportes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellido", "Edad", "horastrab", "pagohora", "sueldo"
            }
        ));
        j.setViewportView(Reportes);

        getContentPane().add(j, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 28, 380, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" REPORTES EMPLEADO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 172, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("REPORTES PRODUCTO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 161, -1));

        Reportes2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Categoria", "Stock", "Nombre", "precio"
            }
        ));
        j2.setViewportView(Reportes2);

        getContentPane().add(j2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 122, 380, 77));

        Reportes3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellido", "Marca", "Cantidad com", "Total a pagar"
            }
        ));
        j3.setViewportView(Reportes3);

        getContentPane().add(j3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 245, 380, 75));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("REPORTES PROVEDORES");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 168, -1));

        regresar.setText("Regresar");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });
        getContentPane().add(regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 326, -1, -1));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1.2.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_regresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reportesto().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Reportes;
    private javax.swing.JTable Reportes1;
    private javax.swing.JTable Reportes2;
    private javax.swing.JTable Reportes3;
    private javax.swing.JScrollPane j;
    private javax.swing.JScrollPane j1;
    private javax.swing.JScrollPane j2;
    private javax.swing.JScrollPane j3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton regresar;
    // End of variables declaration//GEN-END:variables
}
