/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cosas_prod;

import cosas_prod.Consultasp;
import cosas_prod.Bajasp;
import cosas_prod.Reportesp;
import cosas_prod.prod;
import javax.swing.JOptionPane;

/**
 *
 * @author Alan Nava Martinez
 */
public class Menu_productos extends javax.swing.JFrame {

    /**
     * Creates new form Menu_productos
     */
    public Menu_productos() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cons = new javax.swing.JButton();
        Mod = new javax.swing.JButton();
        rep = new javax.swing.JButton();
        sal = new javax.swing.JButton();
        Altas2 = new javax.swing.JButton();
        Bajas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cons.setText("Consultas");
        Cons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsActionPerformed(evt);
            }
        });
        getContentPane().add(Cons, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 121, -1, -1));

        Mod.setText("Modificaciones");
        Mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModActionPerformed(evt);
            }
        });
        getContentPane().add(Mod, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 162, -1, -1));

        rep.setText("Reportes");
        rep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repActionPerformed(evt);
            }
        });
        getContentPane().add(rep, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 197, -1, -1));

        sal.setText("Regresar");
        sal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salActionPerformed(evt);
            }
        });
        getContentPane().add(sal, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 121, -1, -1));

        Altas2.setText("Altas");
        Altas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Altas2ActionPerformed(evt);
            }
        });
        getContentPane().add(Altas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 39, -1, -1));

        Bajas.setText("Bajas");
        Bajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BajasActionPerformed(evt);
            }
        });
        getContentPane().add(Bajas, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 80, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MENU PRODUCTOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 151, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/8.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 190, 100, 130));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/9.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsActionPerformed
        // TODO add your handling code here:
        Consultasp cons = new Consultasp();
        cons = new Consultasp();
        cons.setVisible(true);
    }//GEN-LAST:event_ConsActionPerformed

    private void repActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repActionPerformed
        // TODO add your handling code here:
        Reportesp rep;
        rep = new Reportesp();
        rep.setVisible(true);
    }//GEN-LAST:event_repActionPerformed

    private void salActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_salActionPerformed

    private void Altas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Altas2ActionPerformed
        // TODO add your handling code here:
        prod alt;
        alt = new prod();
        alt.setVisible(true);
    }//GEN-LAST:event_Altas2ActionPerformed

    private void BajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BajasActionPerformed
        // TODO add your handling code here:
        Bajasp ba = new Bajasp();
        ba = new Bajasp();
        ba.setVisible(true);
    }//GEN-LAST:event_BajasActionPerformed

    private void ModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModActionPerformed
        // TODO add your handling code here:
        Modificarp mod = new Modificarp();
        mod = new Modificarp();
        mod.setVisible(true);
        JOptionPane.showMessageDialog(this, "El boton buscar sirve para que veas si existe el id\n"
                + "por si no lo recuerdas");
    }//GEN-LAST:event_ModActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Altas2;
    private javax.swing.JButton Bajas;
    private javax.swing.JButton Cons;
    private javax.swing.JButton Mod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton rep;
    private javax.swing.JButton sal;
    // End of variables declaration//GEN-END:variables
}
